// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Run `flutter pub run build_runner build` to regenerate this file.
//
// This file will be auto-generated by json_serializable package.
// Placeholder file - delete this and run build_runner to generate actual code.

